# Generated by Django 5.2 on 2026-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='template_subject',
            field=models.CharField(blank=True, help_text='Email subject', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
